name: Build README.md

on:
  push:
    branches: [main]
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:

jobs:
  ci:
    name: CI
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/ci.yml
  build:
    name: Build
    permissions:
      contents: write
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm ci
      - name: Build leaderboard
        run: npm run build
      - name: Commit and push changed files
        run: |
          git diff
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add -A
          git commit -m "🤖 Automated update (`date +%FT%T%z`)" || exit 0
          git push
